[build-system]
requires = [
    "setuptools>=42.0.2",
    "setuptools_scm[toml]>=3.3.3",
    "wheel",
]

[tool.black]
line-length = 79
target-version = ["py37","py38"]

[tool.isort]
include_trailing_comma = true
line_length = 79
multi_line_output = 3
known_first_party = ["dsdkexample"]
default_section = "THIRDPARTY"

[tool.setuptools_scm]
